// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Services.Contexts;

#nullable disable

namespace Movies.Api.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20250130143144_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsActorId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorsActorId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("MovieMovieRating", b =>
                {
                    b.Property<int>("MovieRatingsMovieRatingId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieRatingsMovieRatingId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("MovieMovieRating");
                });

            modelBuilder.Entity("Movies.Services.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"));

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            CreatedBy = "",
                            Description = "Robert Anthony De Niro is an American actor and film producer. He is considered to be one of the greatest and most influential actors of his generation.[a] De Niro is the recipient of various accolades, including two Academy Awards and a Golden Globe Award as well as nominations for eight BAFTA Awards and four Emmy Awards. He was honored with the AFI Life Achievement Award in 2003, the Kennedy Center Honors in 2009, the Cecil B. DeMille Award in 2011, and the Screen Actors Guild Life Achievement Award in 2019. De Niro was presented with the Presidential Medal of Freedom by U.S. president Barack Obama in 2016.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/25/Robert_De_Niro_Cannes_2016_2.jpg",
                            Name = "Robert De Niro",
                            UpdatedBy = ""
                        },
                        new
                        {
                            ActorId = 2,
                            CreatedBy = "",
                            Description = "John Joseph Nicholson (born April 22, 1937) is an American retired actor and filmmaker.[1] Nicholson is widely regarded as one of the greatest actors of the 20th century.[2][3] Throughout his five-decade career he received numerous accolades, including three Academy Awards, three BAFTA Film Awards, six Golden Globe Awards, and a Grammy Award. He also received the American Film Institute's Life Achievement Award in 1994 and the Kennedy Center Honor in 2001. In many of his films, he played rebels against the social structure.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ec/Jack_Nicholson_2001.jpg",
                            Name = "Jack Nicholson",
                            UpdatedBy = ""
                        },
                        new
                        {
                            ActorId = 4,
                            CreatedBy = "",
                            Description = "Marlon Brando Jr. (April 3, 1924 – July 1, 2004) was an American actor. Widely regarded as one of the greatest cinema actors of the 20th century,[1][2] Brando received numerous accolades throughout his career, which spanned six decades, including two Academy Awards, three British Academy Film Awards, a Cannes Film Festival Award, two Golden Globe Awards, and a Primetime Emmy Award. Brando is credited with being one of the first actors to bring the Stanislavski system of acting and method acting to mainstream audiences.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Marlon_Brando_publicity_for_One-Eyed_Jacks.png/934px-Marlon_Brando_publicity_for_One-Eyed_Jacks.png",
                            Name = "Marlon Brando",
                            UpdatedBy = ""
                        },
                        new
                        {
                            ActorId = 5,
                            CreatedBy = "",
                            Description = "Denzel Hayes Washington Jr. (born December 28, 1954) is an American actor, producer, and director. Known for his dramatic roles on stage and screen, The New York Times named him the greatest actor of the 21st century in 2020.[2][3] He has received several accolades, including two Academy Awards, three Golden Globe Awards, and a Tony Award as well as nominations for two Emmy Awards and a Grammy Award. Washington has been honored with the Cecil B. DeMille Award in 2016, AFI Life Achievement Award in 2019, and the Presidential Medal of Freedom in 2025.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Denzel_Washington_at_the_2024_Toronto_International_Film_Festival_02_%28cropped%29.jpg/989px-Denzel_Washington_at_the_2024_Toronto_International_Film_Festival_02_%28cropped%29.jpg",
                            Name = "Denzel Washington",
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Movies.Services.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CreatedBy = "",
                            Description = "Making his uber cool and supremely confident directorial debut, Quentin Tarantino hit audiences with a terrific twist on the heist-gone-wrong thriller. For the most part a single location chamber piece, Reservoir Dogs delights in ricocheting the zing and fizz of its dialogue around its gloriously —and indeed gore-iously) — intense setting, with the majority of the movie's action centring around one long and incredibly bloody death scene. Packing killer lines, killer needledrops, and killer, er, killers too, not only is this a rollicking ride in its own right, but it also set the blueprint for everything we've come to expect from a Tarantino joint. Oh, and by the way: Nice Guy Eddie was shot by Mr. White. Who fired twice. Case closed.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5d2d/e61a/853e/7cc4/4bcc/fb99/reservoir-dogs.jpg?auto=format&w=1200&q=80",
                            Name = "Reservoir Dogs",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 2,
                            CreatedBy = "",
                            Description = "Bill Murray is at the height of his (eventually) lovable schmuck powers as narcissistic weatherman Phil Connors. Andie McDowell brings the brains and the heart as distant-but-ever-closer-coming producer Rita Hanson. And Harold Ramis, directing and co-writing with Danny Rubin, manages to spin gold from the well-worn thread of a man stuck in time. Whilst this time-loop dramedy might not have been the first film to drink from this particular trope's well, it is inarguably head and shoulders above the rest. Murray's customarily snarky delivery gets the easy laughs flowing early doors, but it's the way the movie finds deeper things to say about existence and morals as it goes on, all whilst never feeling overly preachy or worthy, that keeps us coming back to it again, and again, and again.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5e67/b5d6/d5e0/0a70/f606/0d1a/2-groundhog-day.jpg?auto=format&w=1200&q=80",
                            Name = "Groundhog Day",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 3,
                            CreatedBy = "",
                            Description = "When the first Paddington was on the way, early trailers didn't look entirely promising. Yet co-writer/director Paul King delivered a truly wonderful film bursting with joy, imagination, kindness, and just the odd hard stare from our beloved Peruvian bear. How was he going to follow that? By making one of the greatest sequels — nay, one of the best, most feel-good movies, period — of all time, naturally. Matching wits with Hugh Grant's moustache-twirlingly evil and deliciously outré washed-up actor Phoenix Buchanan, Paddington (Ben Whishaw) is on typically adorable form here as his search for a special present for his Great Aunt Lucy leads to all sorts of hilarious hijinks. Like all great sequels, this one takes everything that made the first so good and builds on it, dialing up the spectacle, the silliness, and the emotional stakes. The result is as sweet as marmalade.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5e1a/1bb7/d69f/1cb9/e380/fb8f/51-paddington-2.jpg?auto=format&w=1200&q=80",
                            Name = "Paddington 2",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 4,
                            CreatedBy = "",
                            Description = "Jean-Pierre Jeunet's fourth feature – his second as a solo artist divorced from Marc Caro – saw the Delicatessen, The City of Lost Children and Alien: Resurrection filmmaker leave behind the overwhelming darkness of his earlier works and step out into the glorious sunshine of Amélie's whimsical fantasy Paris. Sure, a cynic could read the film as the story of Audrey Tautou's monomaniacal title character's relentless, somewhat stalkerish pursuit of the hapless Nino (Matthieu Kassovitz) around Montmartre's dream-like cityscape. But this one isn't for the cynics — it's a tribute to the daydreamers of this world. It's a sweet, nostalgic, sentimental, beautifully sunny, unforcedly quirky romantic comedy played out amidst a veritable visual fantasia that only Jeunet could have conceived. Amélie will always be on our list of things we like.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5e1d/f8e8/d69f/1c28/ec81/1133/31-amelie.jpg?auto=format&w=1200&q=80",
                            Name = "Amelie",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 5,
                            CreatedBy = "",
                            Description = "A perfect meeting of two creative forces' artistic sensibilities, the Coen brothers' adaptation of Cormac McCarthy's literary great sees the directorial duo imbue the existentialism of McCarthy's book with their signature brand of dark and violent filmmaking. The result is a tense, slow, and mysterious take on the chase movie format, lensed immaculately by legendary DP Roger Deakins. It's also a film that thoughtfully considers the question of how — or even if — good people can ever hope to deal with a world that's entirely gone to shit. And lest we forget, this was the movie that gave us Javier Bardem's cold-blooded sociopathic killer Anton Chigurh, a villain so terrifying that Hollywood has scarcely been able to resist casting Bardem as the go-to bad guy ever since.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5e20/987c/ec7e/5492/ffd5/9229/12-no-country-for-old-men.jpg?auto=format&w=1200&q=80",
                            Name = "No Country For Old Men",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 6,
                            CreatedBy = "",
                            Description = "A high school drama with a time-travelling, tangential universe-threading, sinister rabbit-featuring twist, Richard Kelly's deliberately labyrinthine opus was always destined for cult classic status. A certifiable flop upon its theatrical release, Kelly's film was one of the early beneficiaries of physical media's move to DVD, with the movie gaining a fandom in film obsessives who could pause, play, and skip back and forth through it at will. Any attempt to synopsise the movie is a fool's errand, but there's more than a hint of It's A Wonderful Life in the way we see Donnie (Jake Gyllenhaal, in a star-making turn) experiencing how the world would be worse off if he survives the jet engine that mysteriously crashes through his bedroom. That the film, with all its heavy themes and brooding atmosphere, manages to eventually land on a note of overwhelming optimism is a testament to Kelly's mercurial moviemaking. A mad world (mad world) Donnie Darko's may be, but it's also one that continues to beguile and fascinate as new fans find themselves obsessed with uncovering its mysteries.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5f1a/c758/2c0a/701d/e670/10ca/27-donnie-darko.jpg?auto=format&w=1200&q=80",
                            Name = "Donnie Darko",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 7,
                            CreatedBy = "",
                            Description = "With Scott Pilgrim Vs. The World, Edgar Wright leaned all the way into the things that make his directorial style so singular — excellent needle drops, a poppy visual palette, whip-pans and whip-smart wit — in order to do Bryan Lee O'Malley's beloved graphic novels justice. Michael Cera is on peak socially awkward Cera form here as the eponymous put-upon protagonist who's forced to face his new girlfriend's (Mary Elizabeth Winstead) seven evil exes in a series of increasingly wild face-offs. But it's the film's extraordinarily stacked ensemble (Chris Evans! Brie Larson! Anna Kendrick! Aubrey Plaza!), impressive mixed-media aesthetics, and endless pool of iconic quotes and playlist-essential tunes that cement it as one of Wright's most memorable. This is good garlic bread.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/5f34/0c56/b138/cbc2/3f04/3c09/scott-pilgrim-main.jpg?auto=format&w=1200&q=80",
                            Name = "Scott Pilgrim Vs. The World",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 8,
                            CreatedBy = "",
                            Description = "In some ways, Luc Besson's first English-language movie is a spiritual spin-off: after all, isn't Jean Reno's eponymous hitman just Nikita's Victor The Cleaner renamed and fleshed out? In all seriousness though, Besson's film — which sees Reno's titular contract killer caught up in an unlikely coming-of-age tale after his next-door neighbours wind up on the wrong side of a DEA sting — is very much its own beast. Inarguably, its greatest strength however isn't Reno, or even Gary Oldman's unhinged baddie Stansfield, but a very young Natalie Portman, who delivers a luminous, career-creating performance as vengeful 12-year-old Mathilda. Despite some of the ickiness inherent in the relationship the film presents between a middle-aged man and a pre-teen girl, Portman's phenomenal performance helps augment an unlikely kinship that winds up being deeply affecting to watch.",
                            ImageUrl = "https://images.bauerhosting.com/legacy/media/619d/5ed4/5165/4393/173b/793d/IMG_0294.jpeg?auto=format&w=1200&q=80",
                            Name = "Léon: The Professional",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 9,
                            CreatedBy = "",
                            Description = "If you're going to wrap up your tenure as one of the most loved superhero icons in fiction, it's hard to think of a better way than how Hugh Jackman — under the direction of a never-better James Mangold — punched out on the time clock of playing Wolverine. Set in a dark near-future world where an aging Logan is caring for a mentally unstable Professor Xavier (Patrick Stewart) and getting mixed up yet again with some very dangerous people, Logan takes cues from Western greats such as Shane as Wolvie wrestles with his mortality and history of violence. A truly original superhero tale that is mournful without being morbid, Mangold's mutant masterwork is the perfect end to Logan's story (an ending, it has to be noted, given a rousing yet respectful encore in Deadpool & Wolverine).",
                            ImageUrl = "https://images.bauerhosting.com/empire/2023/09/Logan.jpg?auto=format&w=1200&q=80",
                            Name = "Logan",
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieId = 10,
                            CreatedBy = "",
                            Description = "After his directorial debut Piranha II: Flying Killers fell on its face, James Cameron could've been forgiven for calling it quits on a filmmaking career in Hollywood. Instead, he made The Terminator — and the rest, as they say, is history (which you can read about in detail in our ultimate interview on the movie with Cameron himself). Shot on a $6 million budget, Cameron's sophomore feature may crib a little from Michael Crichton's Westworld and Harlan Ellison's Outer Limits episode 'Soldier', but its action — which revolves around Arnold Schwarzenegger's instantly iconic shot-gun-toting, shades-rocking, time-travelling cyborg killer — is, outside of Cameron's own oeuvre since, without comparison. Made with all the relentless tension of a slasher (after all, what is Arnie's Terminator if not Michael Myers in leathers?) and the kinetic thrills of a balls-to-the-wall blockbuster, nothing has been the same since the T-800 told Linda Hamilton's Sarah Connor \"Come with me if you want to live”.",
                            ImageUrl = "https://images.bauerhosting.com/empire/2024/11/the-terminator-2.jpg?auto=format&w=1200&q=80",
                            Name = "The Terminator",
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Movies.Services.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieActorId"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieActorId = 1,
                            ActorId = 1,
                            CreatedBy = "",
                            MovieId = 1,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 2,
                            ActorId = 2,
                            CreatedBy = "",
                            MovieId = 1,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 3,
                            ActorId = 2,
                            CreatedBy = "",
                            MovieId = 2,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 4,
                            ActorId = 5,
                            CreatedBy = "",
                            MovieId = 2,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 5,
                            ActorId = 2,
                            CreatedBy = "",
                            MovieId = 3,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 6,
                            ActorId = 1,
                            CreatedBy = "",
                            MovieId = 3,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 7,
                            ActorId = 4,
                            CreatedBy = "",
                            MovieId = 4,
                            UpdatedBy = ""
                        },
                        new
                        {
                            MovieActorId = 8,
                            ActorId = 5,
                            CreatedBy = "",
                            MovieId = 4,
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Movies.Services.Models.MovieRating", b =>
                {
                    b.Property<int>("MovieRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieRatingId"));

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovieRatingId");

                    b.ToTable("MovieRatings");

                    b.HasData(
                        new
                        {
                            MovieRatingId = 1,
                            CreatedBy = "",
                            MovieId = 1,
                            UpdatedBy = "",
                            Value = 9m
                        },
                        new
                        {
                            MovieRatingId = 2,
                            CreatedBy = "",
                            MovieId = 1,
                            UpdatedBy = "",
                            Value = 8m
                        },
                        new
                        {
                            MovieRatingId = 3,
                            CreatedBy = "",
                            MovieId = 1,
                            UpdatedBy = "",
                            Value = 8.7m
                        },
                        new
                        {
                            MovieRatingId = 4,
                            CreatedBy = "",
                            MovieId = 2,
                            UpdatedBy = "",
                            Value = 7m
                        },
                        new
                        {
                            MovieRatingId = 5,
                            CreatedBy = "",
                            MovieId = 2,
                            UpdatedBy = "",
                            Value = 6.7m
                        },
                        new
                        {
                            MovieRatingId = 6,
                            CreatedBy = "",
                            MovieId = 2,
                            UpdatedBy = "",
                            Value = 8.1m
                        },
                        new
                        {
                            MovieRatingId = 7,
                            CreatedBy = "",
                            MovieId = 3,
                            UpdatedBy = "",
                            Value = 9.2m
                        },
                        new
                        {
                            MovieRatingId = 8,
                            CreatedBy = "",
                            MovieId = 3,
                            UpdatedBy = "",
                            Value = 9.1m
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Movies.Services.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Services.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieMovieRating", b =>
                {
                    b.HasOne("Movies.Services.Models.MovieRating", null)
                        .WithMany()
                        .HasForeignKey("MovieRatingsMovieRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Services.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movies.Services.Models.MovieActor", b =>
                {
                    b.HasOne("Movies.Services.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Services.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movies.Services.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");
                });
#pragma warning restore 612, 618
        }
    }
}
