name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/MoviesApp/MoviesApp.sln

      - name: Build the solution
        run: dotnet build  ./backend/MoviesApp/MoviesApp.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./backend/MoviesApp/Movies.Tests/Movies.Tests.csproj --configuration Release --no-build 